import{a as b,S as P,i as c}from"./assets/vendor-DxEWe7lX.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const S="50779054-370421c42d6be36ab94d11a5f",q="https://pixabay.com/api/",v=20;async function y(s,o){const r={key:S,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:v};try{return(await b.get(q,{params:r})).data}catch{throw new Error("Sorry, there are no images matching your search query. Please try again!")}}const x=new P(".gallery a",{captionsData:"alt",captionDelay:250}),g=document.querySelector(".gallery"),f=document.querySelector(".loader");function h(s){const o=s.map(r=>`<li class="gallery-item">
        <a href="${r.largeImageURL}">
        <img src="${r.webformatURL}" alt="${r.tags}" class="image">
        </a>
        <div class="description">
        <p class="text">Likes<span class="span">${r.likes}</span></p>
        <p class="text">Views<span class="span">${r.views}</span></p>
        <p class="text">Comments<span class="span">${r.comments}</span></p>
        <p class="text">Downloads<span class="span">${r.downloads}</span></p>
        </div>
        </li>`).join("");g.insertAdjacentHTML("beforeend",o),x.refresh()}function R(){g.innerHTML=""}function m(){f.style.display="block"}function w(){f.style.display="none"}const $=document.querySelector(".form"),l=document.querySelector(".load-button");let i=1,u=15,d="";function p(){l&&l.classList.add("hidden")}function E(){l&&l.classList.remove("hidden")}$.addEventListener("submit",async s=>{var a,e;s.preventDefault();const o=s.target.elements["search-text"],r=o?o.value.trim():"";if(!r){c.warning({title:"Warning",message:"Please enter a search term",position:"topRight"});return}i=1,d=r,R(),m(),p();try{const t=await y(d,i,u),{hits:n}=t;n.length===0?(c.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),p()):(h(n),E());const L=Math.ceil(t.totalHits/u);i>=L&&p()}catch(t){console.error("Error fetching images:",t),c.error({title:"Error",message:((e=(a=t.response)==null?void 0:a.data)==null?void 0:e.message)||"Something went wrong. Please try again later.",position:"topRight"})}finally{w()}});l.addEventListener("click",async()=>{i+=1,m();try{const s=await y(d,i,u);h(s.hits);const o=document.querySelector(".gallery-item");if(o){const a=o.getBoundingClientRect().height;window.scrollBy({top:a*2,behavior:"smooth"})}const r=Math.ceil(s.totalHits/u);i>=r&&(p(),c.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{c.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{w()}});
//# sourceMappingURL=index.js.map
