import{a as b,S as P,i}from"./assets/vendor-DxEWe7lX.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&a(d)}).observe(document,{childList:!0,subtree:!0});function t(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(e){if(e.ep)return;e.ep=!0;const s=t(e);fetch(e.href,s)}})();const S="50779054-370421c42d6be36ab94d11a5f",q="https://pixabay.com/api/",v=15;async function g(o,r){const t={key:S,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:v};try{return(await b.get(q,{params:t})).data}catch{throw new Error("Sorry, there are no images matching your search query. Please try again!")}}const x=new P(".gallery a",{captionsData:"alt",cartionDelay:250}),p=document.querySelector(".gallery"),l=document.querySelector(".loader");document.querySelector(".load-button");function m(o){const r=o.map(t=>`<li class="gallery-item">
        <a href="${t.largeImageURL}">
        <img src="${t.webformatURL}" alt="${t.tags}" class="image">
        </a>
        <div class="description">
        <p class="text">Likes<span class="span">${t.likes}</span></p>
        <p class="text">Views<span class="span">${t.views}</span></p>
        <p class="text">Comments<span class="span">${t.comments}</span></p>
        <p class="text">Downloads<span class="span">${t.downloads}</span></p>
        </div>
        </li>`).join("");p.insertAdjacentHTML("beforeend",r),x.refresh()}function R(){p&&(p.innerHTML="")}function h(){l&&(l.style.display="block")}function w(){l&&(l.style.display="none")}const $=document.querySelector(".form"),f=document.querySelector(".load-button");let u=15,y="",n=1;function c(){f.classList.add("hidden")}function I(){f.classList.remove("hidden")}function L(o,r){return Math.ceil(o/r)}$.addEventListener("submit",async o=>{o.preventDefault();const r=o.target.elements["search-text"],t=r?r.value.trim():"";if(!t){i.warning({title:"Warning",message:"Please enter a search term",position:"topRight"});return}y=t,n=1,R(),h(),c();try{const a=await g(y,n,u),{hits:e,totalHits:s}=a;e.length===0?(i.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),c()):(m(e),I()),n>=L(s,u)&&c()}catch{i.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{w()}});f.addEventListener("click",async()=>{n+=1,h();try{const o=await g(y,n,u);m(o.hits);const r=document.querySelector(".gallery-item");if(r){const t=r.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}n>=L(o.totalHits,u)&&(c(),i.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{i.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{w()}});
//# sourceMappingURL=index.js.map
